//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
#ifndef _RESOURCE_H
#define _RESOURCE_H


#define ID_BUTTON_ADD_ITEM 1001
#define ID_BUTTON2 1002
#define ID_BUTTON_DEL_SELECTED 1003
#define ID_BUTTON_EDIT_ITEM 1004
#define ID_BUTTON5 1005
#define ID_BUTTON6 1006
#define ID_TABLE 1007
#define IDC_BUTTON_CLEAR 1008

#define BUTTONS_WIDTH 140
#define BUTTONS_HEIGHT 30
#define TABLE_OFFSET_X 165

#define IDC_EDIT1 1051
#define IDC_EDIT2 1052
#define IDC_EDIT3 1053
#define IDC_EDIT4 1054
#define IDC_EDIT5 1055
#define ID_ADDITEMDIALOG_BUTTON_ADD 1056
#define IDC_ITEMDIALOG_STATIC_TEXT1 1057
#define IDC_ITEMDIALOG_STATIC_TEXT2 1058
#define IDC_ITEMDIALOG_STATIC_TEXT3 1059
#define IDC_ITEMDIALOG_STATIC_TEXT4 1060
#define IDC_ITEMDIALOG_STATIC_TEXT5 1061
#define ID_EDITITEMDIALOG_BUTTON_EDIT 1062
//#define TEXT_LABEL1 L"Поле №1"
//#define TEXT_LABEL2 L"Поле №2"
//#define TEXT_LABEL3 L"Поле №3"
//#define TEXT_LABEL4 L"Поле №4"
//#define TEXT_LABEL5 L"Поле №5"

#define EDITTEXT1_MAX_LENGTH 40
#define EDITTEXT2_MAX_LENGTH 40
#define EDITTEXT3_MAX_LENGTH 40
#define EDITTEXT4_MAX_LENGTH 40
#define EDITTEXT5_MAX_LENGTH 40





#endif
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
